# Generated by Django 5.2.11 on 2026-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
