# Generated by Django 5.2.11 on 2026-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_department_name_alter_employee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
