# Generated by Django 5.2.11 on 2026-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_employee_created_at_alter_employee_hired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
